apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: bluehat-corp
spec:
  type: organization
  children:
    - admins
    - users
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: bluehat-corp-groups
spec:
  targets:
    - ./admins-group.yaml
    - ./users-group.yaml
