---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admins
  namespace: bluehat
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: users
  namespace: bluehat
spec:
  type: team
  children: []
